SAML_DEBUG is required to be set
[2023-08-21 10:18:14,811] [app.py:1891] ERROR - Exception on /saml/login [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/powerdnsadmin/routes/index.py", line 939, in saml_login
    auth = saml.init_saml_auth(req)
  File "/app/powerdnsadmin/services/saml.py", line 156, in init_saml_auth
    settings['debug'] = current_app.config['SAML_DEBUG']
KeyError: 'SAML_DEBUG'